### ISSUE TITLE
Exclude Execution from inside Lua file

### ISSUE THREAD

**Issue by Antix-Development** [Antix-Development/VSCode-Gideros-Debug#3]
Since Gideros 2020.5 any Lua file whose first line ends with the text _!NOEXEC_ is excluded from execution, which is the same functionality provided by the _excludeFromExecution_ attribute in the projects .gproj file.

Please add this functionality to the extension.

**Comment by Antix-Development** [comment]
Implemented.

NOTE: _!NEEDS_ is currently not supported!

**Comment by hgy29** [comment]
For reference, it is implemented in the dependency graph in Gideros Studio, here: https://github.com/gideros/gideros/blob/master/ui/dependencygraph.cpp#L6
Maybe it would be better to upgrade https://github.com/Antix-Development/VSCode-Gideros-Debug/blob/master/src/GiderosPlayerRemote/DependencyGraph.cs to do the same ?
