### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by Antix-Development** [Antix-Development/VSCode-Gideros-Debug#4]
Some plugins are not working, notably SceneManager and Easing.

It is worth noting that these plugins have no corresponding dll files in the Gideros installation folder.

**Comment by Antix-Development** [comment]
Added code to pass plugins to the player inside the ProjectProperties object but that has not made the plugins work.

I've asked @hgy29 if he can offer any insight.

**Comment by hgy29** [comment]
It should be as 'easy' as integrationg the changes made to Gideros studio there: https://github.com/gideros/gideros/blob/master/ui/librarytreewidget.cpp#L1636
into your code here: https://github.com/Antix-Development/VSCode-Gideros-Debug/blob/master/src/GiderosPlayerRemote/RemoteController.cs#L299

There also a special processing when sending the actual file list to the player here: https://github.com/gideros/gideros/blob/master/ui/mainwindow.cpp#L2515, meant to load plugin files first, to be added somewhere here I reckon: https://github.com/Antix-Development/VSCode-Gideros-Debug/blob/master/src/GiderosPlayerRemote/RemoteController.cs#L182

**Comment by Antix-Development** [comment]
Great. I'll see what I can do. Thanks @hgy29.

**Comment by Antix-Development** [comment]
Thanks for your insights @hgy29 👍 

The extension now checks for the presence of a DLL file corresponding with the plugins name. If a DLL is not found, the extension will include the lua source based plugin from it's luaplugin folder.

NOTE: Currently the extension just uploads the .lua based plugin file as it would with any other .lua file. It does NOT upload it to any special folder.
